<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.lrshuai.langchain4j</groupId>
        <artifactId>langchain4j-demo</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>hello-world</artifactId>

    <dependencies>
        <dependency>
            <groupId>top.lrshuai.langchain4j</groupId>
            <artifactId>common-core</artifactId>
        </dependency>

        <!-- openAi 模型 -->
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-open-ai</artifactId>
        </dependency>

        <!-- 加个logback日志 -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>

    </dependencies>



</project>