server:
  port: 8004


spring:
  application.name: sb-chat-mcp-server

  ai:
    mcp:
      server:
        name: fortuneServer
        annotation-scanner:
          enabled: true
        version: 1.0.0
        type: SYNC
        protocol: STREAMABLE  # SSE or STDIO, STREAMABLE
        streamable-http:
          mcp-endpoint: /mcp
        capabilities:
          tools: true
          logging: true



logging:
  level:
    root: INFO
    top.lrshuai.langchain4j: DEBUG
    dev.langchain4j: DEBUG
